# Generated by Django 3.2.10 on 2023-02-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deatilescustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Password', models.IntegerField(blank=True, max_length=100, null=True)),
                ('confirmpassword', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
