# Generated by Django 3.2.10 on 2023-02-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deatilescustomer',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
