# Generated by Django 3.2.10 on 2023-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactusdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('SUBJECT', models.CharField(blank=True, max_length=100, null=True)),
                ('MESSAGE', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
