# Generated by Django 3.2.10 on 2023-02-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_contactusdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Emailadress', models.CharField(blank=True, max_length=100, null=True)),
                ('Departmentdb', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.TimeField(blank=True, max_length=500, null=True)),
                ('Date', models.DateField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
